name: publish npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Check if token is valid
        run: echo "NPM_AUTH_TOKEN is set"
        env:
          NODE_AUTH_TOKEN: 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

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: 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
